// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/termsandconditions": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/termsandconditions";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/components/termsAndConditions.tsx": {
    id: "routes/components/termsAndConditions";
    page: "/termsandconditions";
  };
};